import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
    await page.goto('http://localhost:3000/login', { waitUntil: 'domcontentloaded' });
    await page.locator('section').filter({ hasText: 'We will never leave your side' }).getByRole('link').click();
    await page.getByRole('textbox', { name: 'Username' }).click();
    await page.getByRole('textbox', { name: 'Username' }).fill('johndoe');
    await page.getByRole('textbox', { name: 'Password' }).click();
    await page.getByRole('textbox', { name: 'Password' }).fill('securepassword');
    await page.getByRole('button', { name: 'Sign In' }).click();
    await page.getByRole('link', { name: 'Loans' }).click();
    await page.getByRole('link', { name: 'Add Loan' }).click();
    await page.getByPlaceholder('Client ID').click();
    await page.getByRole('link', { name: 'Borrowers' }).click();
    await page.getByRole('link', { name: 'Add Borrower' }).click();
    await page.getByRole('textbox', { name: 'First Name' }).click();
    await page.getByRole('textbox', { name: 'First Name' }).fill('test ');
    await page.getByRole('textbox', { name: 'Last Name' }).click();
    await page.getByRole('textbox', { name: 'Last Name' }).fill('user');
    await page.getByPlaceholder('Contact Number').click();
    await page.getByPlaceholder('Contact Number').fill('0710200300');
    await page.getByRole('textbox', { name: 'Address' }).click();
    await page.getByRole('textbox', { name: 'Address' }).click();
    await page.getByRole('textbox', { name: 'Address' }).fill('home');
    await page.getByRole('textbox', { name: 'Email' }).click();
    await page.getByRole('textbox', { name: 'Email' }).fill('test@gmail.com');
    await page.getByRole('textbox', { name: 'Username' }).click();
    await page.getByRole('textbox', { name: 'Username' }).fill('test');
    await page.getByRole('button', { name: 'Save' }).click();
    await page.goto('http://localhost:3000/borrowers');
    await page.getByRole('row', { name: '37 test user 710200300 home' }).getByRole('link').click();
    await page.getByRole('link', { name: 'UPDATE CLIENT' }).click();
    await page.getByRole('textbox', { name: 'First Name' }).click();
    await page.getByRole('textbox', { name: 'First Name' }).fill('test ');
    await page.getByRole('textbox', { name: 'Address' }).click();
    await page.getByRole('textbox', { name: 'Address' }).fill('home, original');
    await page.getByRole('button', { name: 'Update' }).click();
    await page.getByRole('listitem').filter({ hasText: 'Borrowers' }).click();
    await page.getByRole('link', { name: 'Borrowers' }).click();
    await page.getByRole('link', { name: 'Add Borrower' }).click();
    await page.getByRole('textbox', { name: 'First Name' }).click();
    await page.getByRole('textbox', { name: 'First Name' }).fill('test dup email');
    await page.getByRole('textbox', { name: 'Last Name' }).click();
    await page.getByRole('textbox', { name: 'Last Name' }).fill('duplicate email');
    await page.getByPlaceholder('Contact Number').click();
    await page.getByPlaceholder('Contact Number').fill('07102003000');
    await page.getByRole('textbox', { name: 'Address' }).click();
    await page.getByRole('textbox', { name: 'Address' }).fill('home');
    await page.getByRole('textbox', { name: 'Email' }).click();
    await page.getByRole('textbox', { name: 'Email' }).fill('test@gmail.com');
    await page.getByRole('textbox', { name: 'Username' }).click();
    await page.getByRole('textbox', { name: 'Username' }).fill('test');
    await page.getByRole('button', { name: 'Save' }).click();
    await page.getByPlaceholder('Contact Number').click();
    await page.getByPlaceholder('Contact Number').fill('0710200300');
    await page.getByRole('button', { name: 'Save' }).click();
    await page.getByPlaceholder('Contact Number').click();
    await page.getByPlaceholder('Contact Number').fill('071020030');
    await page.getByRole('button', { name: 'Save' }).click();
    await page.getByPlaceholder('Contact Number').click();
    await page.getByRole('textbox', { name: 'Last Name' }).click();
    await page.getByRole('textbox', { name: 'Last Name' }).fill('duplicate');
    await page.getByText('First Name: Last Name:').click();
    await page.getByRole('textbox', { name: 'First Name' }).click();
    await page.getByRole('textbox', { name: 'First Name' }).fill('test_dup_email');
    await page.getByRole('button', { name: 'Save' }).click();
    await page.getByRole('link', { name: 'Borrowers' }).click();
    await page.getByRole('row', { name: '38 test dup email duplicate' }).getByRole('link').click();
    await page.getByText('test@gmail.com').click();
    await page.getByRole('link', { name: 'Borrowers' }).click();
    await page.getByRole('link', { name: 'Add Borrower' }).click();
    await page.getByRole('textbox', { name: 'First Name' }).click();
    await page.getByRole('textbox', { name: 'First Name' }).fill('long contact');
    await page.getByRole('textbox', { name: 'Last Name' }).click();
    await page.getByRole('textbox', { name: 'Last Name' }).fill('number');
    await page.getByPlaceholder('Contact Number').click();
    await page.getByPlaceholder('Contact Number').fill('254710200200');
    await page.getByRole('textbox', { name: 'Address' }).click();
    await page.getByRole('textbox', { name: 'Address' }).fill('home ');
    await page.getByRole('textbox', { name: 'Email' }).click();
    await page.getByRole('textbox', { name: 'Email' }).fill('longcont@gmail.com');
    await page.getByRole('textbox', { name: 'Username' }).click();
    await page.getByRole('textbox', { name: 'Username' }).fill('long');
    await page.getByRole('button', { name: 'Save' }).click();
    await expect(page.locator('form')).toMatchAriaSnapshot(`- button "Save"`);
    await page.getByRole('textbox', { name: 'Last Name' }).click();
    await page.getByRole('button', { name: 'Cancel' }).click();
    await page.getByRole('row', { name: '38 test dup email duplicate' }).getByRole('button').first().click();
    await page.getByRole('row', { name: '39 test dup email duplicate' }).getByRole('button').first().click();
    await page.getByRole('row', { name: '40 test_dup_email duplicate' }).getByRole('button').first().click();
    await page.getByRole('row', { name: '37 test user 710200300 home,' }).getByRole('button').first().click();
});